# Generated by Django 5.1.4 on 2024-12-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatar.png', upload_to='recipe/avatars/', verbose_name='avatar'),
        ),
    ]
