# Generated by Django 5.1.4 on 2024-12-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='account_id'),
        ),
    ]
