# Generated by Django 5.1.4 on 2024-12-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(default='', max_length=30, verbose_name='account_name'),
            preserve_default=False,
        ),
    ]
