# Generated by Django 5.1.4 on 2024-12-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatar.png', null=True, upload_to='recipe/avatars/', verbose_name='avatar'),
        ),
    ]
