# Generated by Django 5.1.4 on 2024-12-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='defaults/avatar.png', upload_to='recipe/avatars/', verbose_name='avatar'),
        ),
    ]
