# Generated by Django 5.1.3 on 2024-12-04 00:25

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_recipe_recipe_id_recipe_title_alter_recipe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updateded_at'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='recipe_id'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('DELETED_USER'), to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
