# Generated by Django 5.1.3 on 2024-12-04 00:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipe_created_at_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='recipe_code'),
        ),
    ]
