# Generated by Django 5.1.3 on 2024-12-04 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_recipesection_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('count', models.CharField(max_length=128, verbose_name='count')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe', verbose_name='recipe')),
            ],
        ),
    ]
