# Generated by Django 5.1.3 on 2024-12-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_ingredientssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientssection',
            name='index_num',
            field=models.IntegerField(default=0, verbose_name='index_num'),
            preserve_default=False,
        ),
    ]
