# Generated by Django 5.1.3 on 2024-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_ingredientssection_index_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientssection',
            name='count',
        ),
        migrations.AddField(
            model_name='ingredientssection',
            name='amount',
            field=models.CharField(default='', max_length=128, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
