# Generated by Django 5.1.3 on 2024-12-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_remove_ingredientssection_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_code',
            field=models.CharField(max_length=11, unique=True, verbose_name='recipe_code'),
        ),
    ]
