# Generated by Django 5.1.3 on 2024-12-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_alter_recipe_recipe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public_level',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Limited and private'), (2, 'Public')], default=0, verbose_name='public_level'),
        ),
    ]
