# Generated by Django 5.1.4 on 2024-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.BigIntegerField(default=0, verbose_name='favorite_count'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='public_level',
            field=models.IntegerField(choices=[(0, '非公開'), (1, '限定公開'), (2, '公開')], default=0, verbose_name='public_level'),
        ),
    ]
