# Generated by Django 5.1.4 on 2024-12-12 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0015_alter_recipe_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='default_thumbnail.png', upload_to='recipe/thumbnails/', verbose_name='recipe_image'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe', verbose_name='recipe')),
                ('user', models.ForeignKey(on_delete=models.SET('DELETED_USER'), to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
