# Generated by Django 5.1.4 on 2024-12-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0017_recipe_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='defaults/thumbnail.png', upload_to='recipe/thumbnails/', verbose_name='recipe_image'),
        ),
    ]
