# Generated by Django 5.1.4 on 2024-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0018_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='recipe/thumbnails/', verbose_name='recipe_image'),
        ),
    ]
