# Generated by Django 5.1.4 on 2024-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0019_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='deleted_at'),
        ),
    ]
