# Generated by Django 5.1.4 on 2024-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0020_recipe_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
